<a href="https://colab.research.google.com/github/israellmorais/ReconhecimentodePadroes/blob/main/ExGeneralizacaoNovo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercício de Generalização - Reconhecimento de Padrões
Aluno: Israel de Morais Madalena
Professor: Francisco Boldt

Escolha uma base de classificação e compare os classificadores Logistic Regression e KNN do scikit-learn.

Use pelo menos duas formas de avaliação e as repita pelo menos 10 vezes.

Calcule a média das repetições de cada avaliação.

###Bibliotecas

In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, make_scorer
from sklearn.model_selection import cross_validate
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

###Pré-processamento

In [40]:
wine = load_wine()
wine.keys()

X, y = wine.data, wine.target

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.33, random_state=42)

X.shape, y.shape, set(y), X_treino.shape, X_teste.shape, y_treino.shape, y_teste.shape

((178, 13), (178,), {0, 1, 2}, (119, 13), (59, 13), (119,), (59,))

###Com padronização (GridSearch e cross validate)

In [65]:
def knc_compad(i):   
    parametros = {'n_neighbors': [1,3,5,7,9]}

    GridSearchKNC = GridSearchCV(KNeighborsClassifier(), parametros, scoring=make_scorer(accuracy_score),cv=i)

    modelo = Pipeline([
        ("padronização", StandardScaler()),
        ("gsknc", GridSearchKNC)
        ])
    scores = cross_validate(modelo, X, y)
    print(scores['test_score'])
    compad = np.mean(scores['test_score'])
    print(f"Com padronização: {compad}")
    return compad

In [64]:
from sklearn.model_selection import GridSearchCV
def logisticr_compad(i):
    parameters = {}

    #logisticr = GridSearchCV(LogisticRegression(),parameters,cv=10,return_train_score=True)
    logisticr = GridSearchCV(LogisticRegression(penalty = 'l2', C = i,random_state = 0),parameters,cv=i,scoring=make_scorer(accuracy_score))

    modelo = Pipeline([
        ("padronização", StandardScaler()),
        ("gslogistic", logisticr)
        ])
    scores = cross_validate(modelo, X, y)
    print(scores['test_score'])
    compad = np.mean(scores['test_score'])
    print(f"Com padronização: {compad}")
    return compad

###Sem padronização

In [63]:
def knc_sempad(i):
    modelo = KNeighborsClassifier()
    scores = cross_validate(modelo, X, y, scoring=make_scorer(accuracy_score),cv=i)
    print(scores['test_score'])
    sempad = np.mean(scores['test_score'])
    print(f"Sem padronização: {sempad}")
    return sempad

In [62]:
def logisticr_sempad(i):
    modelo = LogisticRegression()
    scores = cross_validate(modelo, X, y, scoring=make_scorer(accuracy_score))
    print(scores['test_score'])
    sempad = np.mean(scores['test_score'])
    print(f"Sem padronização: {sempad}")
    return sempad

In [79]:
logistic_sempad = []
logistic_compad = []
kncl_sempad = []
kncl_compad = []


for i in range(10):
  logistic_sempad.append(logisticr_sempad(i+2))
  logistic_compad.append(logisticr_compad(i+2))
  kncl_sempad.append(knc_sempad(i+2))
  kncl_compad.append(knc_compad(i+2))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555
[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.61797753 0.70786517]
Sem padronização: 0.6629213483146067
[0.97222222 0.94444444 0.97222222 1.         0.97142857]
Com padronização: 0.972063492063492
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.61666667 0.61016949 0.76271186]
Sem padronização: 0.6631826741996234
[0.94444444 0.94444444 0.97222222 1.         0.97142857]
Com padronização: 0.9665079365079364


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555
[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.66666667 0.66666667 0.68181818 0.72727273]
Sem padronização: 0.6856060606060606
[0.94444444 0.94444444 0.97222222 1.         0.91428571]
Com padronização: 0.9550793650793651
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.72222222 0.66666667 0.63888889 0.65714286 0.77142857]
Sem padronização: 0.6912698412698413
[0.94444444 0.94444444 0.97222222 1.         0.91428571]
Com padronização: 0.9550793650793651


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555
[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.7        0.66666667 0.63333333 0.7        0.72413793 0.72413793]
Sem padronização: 0.6913793103448276
[0.94444444 0.94444444 0.97222222 1.         0.97142857]
Com padronização: 0.9665079365079364
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.69230769 0.65384615 0.69230769 0.68       0.72       0.72
 0.76      ]
Sem padronização: 0.7026373626373627
[0.94444444 0.94444444 0.97222222 0.97142857 0.97142857]
Com padronização: 0.9607936507936508
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 1.         0.97142857 1.        ]
Com padronização: 0.9831746031746033
[0.69565217 0.69565217 0.5        0.68181818 0.63636364 0.77272727
 0.72727273 0.81818182]
Sem padronização: 0.6909584980237153
[0.94444444 0.94444444 0.97222222 1.         0.97142857]
Com padronização: 0.9665079365079364
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 0.97222222 0.97142857 1.        ]
Com padronização: 0.9776190476190475
[0.7        0.6        0.65       0.6        0.75       0.65
 0.7        0.78947368 0.78947368]
Sem padronização: 0.6921052631578948
[0.94444444 0.94444444 0.97222222 1.         0.97142857]
Com padronização: 0.9665079365079364
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 0.97222222 0.97142857 1.        ]
Com padronização: 0.9776190476190475
[0.66666667 0.66666667 0.61111111 0.61111111 0.61111111 0.61111111
 0.72222222 0.66666667 0.82352941 0.76470588]
Sem padronização: 0.6754901960784313
[0.94444444 0.94444444 0.97222222 0.97142857 0.91428571]
Com padronização: 0.9493650793650794
[0.88888889 0.94444444 0.94444444 1.         1.        ]
Sem padronização: 0.9555555555555555


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.97222222 0.97222222 0.97222222 0.97142857 1.        ]
Com padronização: 0.9776190476190475
[0.76470588 0.64705882 0.75       0.5        0.5625     0.75
 0.625      0.8125     0.875      0.75       0.75      ]
Sem padronização: 0.7078877005347594
[0.94444444 0.94444444 0.97222222 1.         0.91428571]
Com padronização: 0.9550793650793651


###Resultados

In [84]:
print('KNC sem padronização: ',np.mean(kncl_sempad))
print('Logistic Regression sem padronização: ',np.mean(logistic_sempad))
print('\n\nKNC com padronização: ',np.mean(kncl_compad))
print('Logistic Regression com padronização: ',np.mean(logistic_compad))

KNC sem padronização:  0.6863438255167122
Logistic Regression sem padronização:  0.9555555555555555


KNC com padronização:  0.9613492063492064
Logistic Regression com padronização:  0.9815079365079364


####Conclusão
Observa-se que o KNC sem padronização obteve um valor bem diferente do Logistic Regression, evidenciando que os resultados podem ser melhorados com a padronização. Ao se padronizar, verificou-se que o KNeighborsClassifier ficou bem próximo do valor obtido pelo Logistic Regression. Na padronização foi utilizado o Grid Search e o Cross Validate.